#!/usr/bin/env python3

#------------------------------------- Imported Modules ---------------------------------------
# os: allows python to interact directly with the OS file structure(changing file permissions)
# sqlite3: provides database API to connect to ("classes.db")
# subprocess: allows python to directly execute native Bash commands from within the code.
#----------------------------------------------------------------------------------------------
import os
import sqlite3
import subprocess

# =====================
# FUNCTIONS
# =====================

# ====================================================================================
def presentation_data():

    connect = sqlite3.connect("classes.db")
    pointer = connect.cursor()

    pointer.execute("DROP TABLE IF EXISTS classes;")

    pointer.execute("""
        CREATE TABLE IF NOT EXISTS classes (
            id		        INTEGER PRIMARY KEY
            course_name		VARCHAR(100) NOT NULL,
            grade_point_average	DOUBLE NOT NULL,
            units	        INTEGER NOT NULL
	    term		TEXT
        );
    """)

    # sample data
    sample_data = [
        ('Calculus 3', 3.5, 4, 'Fall 2026'),
        ('Physics 205', 3.2, 3, 'Fall 2026'),
        ('History 1B', 4, 3, 'Spring 2027'),
        ('Ethnic Studies', 3.2, 3, 'Summer 2026')
    ]

    pointer.executemany("""
        INSERT INTO classes (course_name, grade_point_average, units, term) VALUES (?, ?, ?, ?);
    """, sample_data)

    connect.commit()
    connect.close()

# =====================================================================================
def greetings():
    # command 1 (Bash): clear -> clears terminal screen
    subprocess.run(["clear"])

    # command 2 (Bash): whoami -> prints exact username of current user ID
    user_proc = subprocess.run(["whoami"]), capture_output=True, text=True)
    username = user_proc.stdout.strip()

    # command 3 (Bash): date -> displays current date and time
    date_proc = subprocess.run(["date"]), capture_output=True, text=True)
    current_date = date_proc.stdout.strip()

    # command 4 (Bash): uptime -> gets host performance stats
    uptime_proc = subprocess.run(["uptime"]), capture_output=True, text=True)
    sys_status = uptime_proc.stdout.strip()

    print("--------------------------------------------------------------"
    print(f" Welcome to TerminalGPAMetrics, {username}")
    print(f" Session Started: {current_date}")
    print(f" System Status: {sys_status}")

# ====================================================================================
def display_data_table(cursor):
    output_method = input("choose ouput method(In Program or HTML): ")

    if output_method == "In Program":
        #pulls records from database to format for terminal output
        cursor.execute("SELECT course_name, units, grade_point_average, term FROM classes;")
        records = cursor.fetchall()

        if not records:
            print("No records found.")
            return

        #creating file and setting reference variable
        temp_file = "temp_gpa_data.txt"
        with open(temp_file, "w") as f:
            #printing rows from records into file
            for row in records:
                f.write(f"{row[0]}|{row[1]}|{row[2]}|{row[3]}\n")

	# command 5 (Bash): wc -l -> counts number of entries exported to file
	lines_proc = subprocess.run(["wc", "-l", temp_file], capture_output=True, text=True)
	total = lines_proc.stdout.strip().split()[0]}
	print(f"\nTotal active records processed: {total}")

	print("\n----- Data Table (formatted in AWK) -----")

	# command 6 (Bash) awk -> formats lines into structured columns
	awk = (
	    'BEGIN {FS="|"; printf "%-20s | %-6s | %-12s | %-12s\n", "Course Name", "Units", "Grade Point", "Term";'
            ' print "-----------------------------------------------------------------"}'
            '{printf "%-20s | %-6s | %-12s | %-12s\n", $1, $2, $3, $4}'
	)
	#runs the data file into formated version with awk
	subprocess.run(["awk", awk, temp_file])

	#deletes temp file
	if os.path.exists(temp_file):
	    os.remove(temp_file)

    elif output_method = "HTML":
        #calling group members external HTML report
	#CHANGE generate_report_placeholder.sh to actual file name
	subprocess.run(["bash", "generate_report_placeholder.sh"])

	print("\nHTML report generation complete. Verifying file safety properties:")

	# command 7 (Bash): ls -l -> verifies permmissions of the file
	subprocess.run(["ls", "-l", "gpa_report.html"])

    else:
	print("\nInvalid output method selection.")

# =======================================================================================
def calc_gpa(cursor):
    #pulling existing records to calculate gpa
    cursor.execute("SELECT grade_point_average, units FROM classes;")
    records = cursor.fetchall()

    #if no records found
    if not records:
        print("Unable to calculate GPA, no course records found.")
        return

    total_points = 0.0
    total_units = 0

    #sum of total grade points and units
    for row in records:
        grade_val =  row[0]
        units = row[1]
        total_points += (grade_val * units)
        total_units += units

    #checking if total units is equal to 0 to avoid error
    if total_units == 0:
        print("\nTotal units cannot be zero.")
        return

    #calcuclated final gpa
    final_gpa = (total_points / total_units)
    print(f"Final Calculated GPA: {final_gpa:.2f}")

# ========================================================================================
def edit_data_table(connection, cursor):
    #command 8 (Bash): cp -> copies the database to create a backup file
    print("Saving data to backup file...")
    subprocess.run(["cp", "classes.db", "classes.db.bak"])

    change_method = input("Select an edit method (Add, Delete, or Change): ").strip.lower()

    # add method
    if change_method == "add":
        new_course = input("Enter course name: ")
        new_units = int(input("Enter units: "))
        new_grade = float(input(("Enter letter grade: "))
        new_term = input("Enter term: ")

        cursor.execute(
            "INSERT INTO classes (course_name, units, grade_point_average, term) VALUES (?, ?, ?, ?);",
            (new_course, new_units, new_grade, new_term)
        )
        connection.commit()
        print("Course successfully added!")

    # delete method
    elif change_method == "delete":
        delete_target = input("Enter the course name you want to remove: ")

        cursor.execute(
            "DELETE FROM classes WHERE course_name = ?;", (delete_target)
        )
        connection.commit()
        print("Course successfully removed!")

    # change method
    elif change_method == "change":
        update_target = input("Enter the course name you want to update: ")
        update_field = input("Which field do you want to change (Grade, Units, or Term)?: ").strip().lower()
        new_value = input("Enter the new value: ")

        #updating fild based on users update field selection
        if update_field == "grade":
            cursor.execute("UPDATE classes SET grade_point_average = ? WHERE course_name = ?;", (float(new_value), update_target))
        elif update_field == "units":
            cursor.execute("UPDATE classes SET units = ? WHERE course_name = ?;", (int(new_value), update_target))
        elif update_field == "term":
            cursor.execute("UPDATE classes SET term = ? WHERE course_name = ?;", (new_value, update_target))
	else:
	    print("Invalid field selection.")
	    return

        connection.commit()
        print("Course sucessfully updated!")

    else:
        print("Invalid edit method selection.")

# =========================================================================================
def search_function(cursor):
    print("---Course Search---")
    print("Press Enter to skip filter."

    #gathering users search filters
    search_term = input("Filter Search by Term: ").strip()
    search_course = input("Filter Search by Course Name: ").strip()

    #gathering record based on what user provided
    #LIKE used for searching for pattern based on users input
    record = "SELECT (course_name, units, grade_point_average, term) FROM classes WHERE term LIKE ?, course_name LIKE ?;"
    parameters = (f"%{search_term}%"), (f"%{search_course}%")

    cursor.execute(records, parameters)
    results = cursor.fetchall()

    #if no results found print message
    if not results:
        print("No classes matched your search criteria.")
        return

    #creating file to hold search results
    temp_file = "search.txt"
    with open(temp_file, "w") as f:
        #inserting results into file
        for row in results:
            f.write(f"Course: {row[0]} | Units: {row[1]} | Grade Point: {row[2]} | Term: {row[3]}\n")

    print("\nSearch Results: ")
    # command 9 (Bash): grep -> Searches for specific text pattern(displays exactly what was filtered in SQLite)
    subprocess.run(["grep", "-i", "", temp_file])

    #deleting temp_file
    if os.path.exists(temp_file):
        os.remove(temp_file)

# ========================================================================================


# ===================================
# Main code
# ===================================

# creates database table and inserts sample course data
presentation_data()

db_file = "classes.db"

# Open persistent connection pipeline using original variable layouts
connection = sqlite3.connect(db_file)
cursor = connection.cursor()

greetings()

# Main Application Loop
while True:
    print("\n--- MAIN MENU ---")
    print("1. Display Data Table")
    print("2. Calculate GPA")
    print("3. Edit Data Table")
    print("4. Search Function")
    print("5. Check File Size")
    print("6. Exit")

    #prompts user to select from menue
    user_selection = input("Select an option from the menu (1-6): ").strip()

    if user_selection == "6" or user_selection.lower() == "exit":
        print("Exiting program.")
        break

    elif user_selection == "1" or user_selection.lower() == "display data table":
        display_data_table(cursor)

    elif user_selection == "2" or user_selection.lower() == "calculate gpa":
        calc_gpa(cursor)

    elif user_selection == "3" or user_selection.lower() == "edit data table":
        edit_data_table(connection, cursor)

    elif user_selection == "4" or user_selection.lower() == "search function":
        search_function(cursor)

    elif user_selection == "5":
        print("\n--- Disk Usage Info ---")
        # command 10 (Bash): du -sh -> Calculates memory layout summary of database file on hardware
        subprocess.run(["du", "-sh", db_file])

    else:
        print("Invalid selection. Please try again.")

    # option to break loop back to main screen
    user_choice = input("\nReturn to the main menu? (Yes/No): ").strip().lower()
    if user_choice == "no":
        print("Exiting program.")
        break

connection.close()





